# NOTE: Currently starting off at 753.8 MB
FROM vovimayhem/dev-stack-base-ruby:latest
MAINTAINER Roberto Quintanilla <roberto.quintanilla@gmail.com>
# We'll do nothing :) This waste will last until Docker Hub allows some form of
# chaining automated builds from within the same project. (We should help!)
